// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/angular-spinner/angular-spinner.d.ts
interface ISpinnerService {
    /**
     * Start selected spinner
     * 
     * @param spinner key
     */
    spin(key: string): void;

    /**
     * Stop selected spinner
     * 
     * @param spinner key
     */
    stop(key: string): void;
}
